managers:
  #---------------------------------------------------------------
  - name: Fail if missing coordinates
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.FailPipeline
        parameters:
          context: Coordinate variables cannot be missing.
    apply_to:
      - COORDS

  - name: Fail if monotonic coordinates
    checker:
      classname: tsdat.qc.checkers.CheckMonotonic
      parameters:
        require_increasing: true
    handlers:
      - classname: tsdat.qc.handlers.FailPipeline
        parameters:
          context: Coordinate variables must be strictly increasing.
    apply_to:
      - time

    #---------------------------------------------------------------
  - name: Remove missing data
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.RemoveFailedValues
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 1
          assessment: bad
          meaning: "Value is equal to _FillValue or NaN"
    apply_to:
      - DATA_VARS

  - name: Despiking Quality Check and Corrections
    checker:
      classname: pipelines.waves.qc.GoringNikora2002
      parameters:
        n_points: 1000
    handlers:
      - classname: pipelines.waves.qc.CubicSplineInterp
        parameters:
          npt: 12
          method: "cubic"
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 2
          assessment: bad
          meaning: "Spike"
    apply_to:
      - displacement

  - name: Flag data below minimum failure threshold
    checker:
      classname: tsdat.qc.checkers.CheckValidMin
    handlers:
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 3
          assessment: bad
          meaning: "Value is less than the valid_range."
    apply_to:
      - displacement

  - name: Flag data above maximum failure threshold
    checker:
      classname: tsdat.qc.checkers.CheckValidMax
    handlers:
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 4
          assessment: bad
          meaning: "Value is greater than the valid_range."
    apply_to:
      - displacement
